### ISSUE TITLE
Get title from domain

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [buttercup/buttercup#201]
Hi
I recently use buttercup.
Something I notice in my first uses is title is necessary and it's painful to fill it every time, is possible to fill title automatically from domain name; something like this: for domain name _github.com_ title become _github_

**Comment by perry-mitchell** [comment]
I quite like the idea, but is the domain something you fill in first @MahdiMajidzadeh? When I create credentials, for instance, title is usually the first thing I enter. In the browser extension I can see this being quite simple.

For this we could add detection so that:

1. User stops typing URL field (URL/url)
2. Check that the title is empty
3. Set title to domain part

**Comment by perry-mitchell** [comment]
Hi @MahdiMajidzadeh - Just looking for your input on your usage of buttercup for this item. I can't currently see how this would work for "regular" use (I'm biased here obviously), and it'd be great if you could explain how you'd expect it to work.

**Comment by sallar** [comment]
Im suspecting that this is related to the browser extension and not this repo. One example is 1password's functionality: when you click sign in or sign up, and it offers to save the password for the current site, it has alreay filled in the title for you (based on the current page's title).

**Comment by MahdiMajidzadeh** [comment]
@sallar said what I mean

**Comment by perry-mitchell** [comment]
Closed as the functionality will be handled by buttercup-pw/buttercup-browser-extension#58
