### ISSUE TITLE
[Enhancement] Unlock automatically Firefox extension

### ISSUE THREAD

**Issue by simonbcn** [buttercup/buttercup#288]
When I open Firefox, the extension is locked. The security is good but in my personal computer (_in my home_) isn't necessary. The current behavior is annoying. I should be able to decide to automatically unlock the database.

**Comment by perry-mitchell** [comment]
Hi @simonbcn - As we only have memory and localstorage really in the browser, we don't have many options in storing archives. We won't be encrypting your master password so that it stays open between browser sessions, and once you close your browser and re open it it has to be in the locked state as the memory was wiped.

**Comment by perry-mitchell** [comment]
Unfortunately this repo is also just for the desktop application, so I'll have to close this issue. Please open another issue [here](https://github.com/buttercup/buttercup-browser-extension) if you have a suggested implementation in mind. Sorry for the inconvenience.
